export enum postTypes {
  FETCH_POST_REQUEST = 'FETCH_POST_REQUEST',
  FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS',
  FETCH_POST_FAILURE = 'FETCH_POST_FAILURE',
  SWITCH_COMPLETED_REQUEST = 'SWITCH_COMPLETED_REQUEST',
  SWITCH_COMPLETED_SUCCESS = 'SWITCH_COMPLETED_SUCCESS',
  SWITCH_COMPLETED_FAILURE = 'SWITCH_COMPLETED_FAILURE',
  CREATE_TODO_REQUEST = 'CREATE_TODO_REQUEST',
  CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS',
  CREATE_TODO_FAILURE = 'CREATE_TODO_FAILURE',
  DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST',
  DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS',
  DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE'
  
}